modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/crispytwig/Sweet-and-Savory/issues"

[[mods]]
modId = "sweet_n_savory"
version = "${version}"
displayName = "Sweet n' Savory"
#updateJSONURL="http://myurl.me/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sweet_n_savory"
logoFile = "icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "crispytwig"
description = '''
Decorative blocks out of scope to Another Furniture
'''

[[dependencies.sweet_n_savory]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sweet_n_savory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
